[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Proxy API requests to your backend server
[[redirects]]
  from = "/api/*"
  to = "https://suret-meat-market-api-production.up.railway.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
